# Generated by Django 3.1.7 on 2021-03-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='modification',
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_fuel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.CharField(max_length=100),
        ),
    ]
