# Generated by Django 3.1.7 on 2021-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210328_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_fuel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
