# Generated by Django 3.1.7 on 2021-03-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210328_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
