# Generated by Django 3.1.7 on 2021-04-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=50)),
                ('generation', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('volume', models.PositiveIntegerField()),
                ('power_range_from', models.PositiveIntegerField()),
                ('power_range_to', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('production_from', models.DateField()),
                ('production_to', models.DateField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.model')),
            ],
        ),
    ]
