# Generated by Django 3.1.7 on 2021-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210404_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='production_period',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='modification',
            name='power_range',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
