# Generated by Django 3.1.7 on 2021-05-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_queryresult'),
        ('wish_list', '0003_auto_20210508_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
    ]
