# Generated by Django 3.1.7 on 2021-04-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210406_2025'),
        ('user_profile', '0004_auto_20210404_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine_fuel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_volume',
        ),
        migrations.AddField(
            model_name='car',
            name='modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modification'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.generation'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.model'),
        ),
    ]
