# Generated by Django 3.1.7 on 2021-04-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210407_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='last_searched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
